#
# @file  appveyor.yml
# @brief AppVeyor continuous integration config file for the Motion SDK classes.
#.       Build and run unit tests on Windows with Visual Studio.
#
version: 1.0.{build}

image: Visual Studio 2017

configuration: Release

platform:
  - x64
  - Win32

build:
  verbosity: minimal

test_script:
- cmd: python test\test_server.py build\bin\%PLATFORM%\%CONFIGURATION%\test_MotionSDK.exe